# Generated by Django 6.0.5 on 2026-06-02 12:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание товара')),
                ('image1', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('image2', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('image3', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20, verbose_name='Рейтинг товара')),
                ('discount', models.CharField(choices=[(5, '5%'), (10, '10%'), (20, '20%'), (30, '30%')], max_length=20, verbose_name='Скидка на товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
