# Generated by Django 6.0.5 on 2026-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('5', 5), ('10', 10), ('20', 20), ('30', 30)], max_length=20, verbose_name='Скидка на товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, verbose_name='Рейтинг товара'),
        ),
    ]
